### ISSUE TITLE
Error in Outline when editing Xtend file

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1034]
```
505184 [Worker-3: Refreshing Outline] ERROR org.eclipse.xtext.ui.editor.outline.impl.OutlineRefreshJob  - Error refreshing outline
java.lang.IllegalArgumentException: Unhandled parameter types: [org.eclipse.xtext.ui.editor.model.XtextDocument@35ae7e38]
	at org.eclipse.xtend.ide.labeling.XtendLabelProvider.imageDescriptor(XtendLabelProvider.java:299)
	at org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider.doGetImage(XbaseLabelProvider.java:272)
	at org.eclipse.xtext.ui.label.AbstractLabelProvider.getImageDescriptor(AbstractLabelProvider.java:67)
	at org.eclipse.xtext.ui.editor.outline.impl.BackgroundOutlineTreeProvider.getImageDescriptor(BackgroundOutlineTreeProvider.java:134)
	at org.eclipse.xtext.ui.editor.outline.impl.BackgroundOutlineTreeProvider.createRoot(BackgroundOutlineTreeProvider.java:63)
	at org.eclipse.xtext.ui.editor.outline.impl.BackgroundOutlineTreeProvider.createRoot(BackgroundOutlineTreeProvider.java:71)
	at org.eclipse.xtend.ide.outline.XtendOutlineTreeProvider.createRoot(XtendOutlineTreeProvider.java:56)
	at org.eclipse.xtext.ui.editor.outline.impl.OutlineRefreshJob$2.createModel(OutlineRefreshJob.java:103)
	at org.eclipse.xtext.ui.editor.outline.impl.OutlineRefreshJob$2.exec(OutlineRefreshJob.java:93)
	at org.eclipse.xtext.ui.editor.outline.impl.OutlineRefreshJob$2.exec(OutlineRefreshJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.ui.editor.outline.impl.OutlineRefreshJob.internalRefreshOutlineModel(OutlineRefreshJob.java:90)
	at org.eclipse.xtext.ui.editor.outline.impl.OutlineRefreshJob.refreshOutlineModel(OutlineRefreshJob.java:74)
	at org.eclipse.xtext.ui.editor.outline.impl.OutlineRefreshJob.run(OutlineRefreshJob.java:56)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by cdietrich** [comment]
might be fallout of xtend migration

**Comment by cdietrich** [comment]
Fixed
