### ISSUE TITLE
Build seems to ignore crashing tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1088]
https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_java11_experiments/17/console

```
 [INFO] Executing Test Runtime with timeout 0, logs (if any) will be placed at: /home/jenkins/agent/workspace/text-xtend_cd_java11_experiments/org.eclipse.xtend.ide.tests/target/work/data/.metadata/.log
 [INFO] Command line:
 	[/usr/lib/jvm/java-11-openjdk-11.0.7.10-1.fc31.x86_64/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Xmx2G, -Dosgi.clean=true, -jar, /home/jenkins/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.5.800.v20200727-1323/org.eclipse.equinox.launcher-1.5.800.v20200727-1323.jar, -data, /home/jenkins/agent/workspace/text-xtend_cd_java11_experiments/org.eclipse.xtend.ide.tests/target/work/data, -install, /home/jenkins/agent/workspace/text-xtend_cd_java11_experiments/org.eclipse.xtend.ide.tests/target/work, -configuration, /home/jenkins/agent/workspace/text-xtend_cd_java11_experiments/org.eclipse.xtend.ide.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /home/jenkins/agent/workspace/text-xtend_cd_java11_experiments/org.eclipse.xtend.ide.tests/target/surefire.properties, -pluginCustomization, /home/jenkins/agent/workspace/text-xtend_cd_java11_experiments/org.eclipse.xtend.ide.tests/../releng/org.eclipse.xtend.tycho.tests.parent/pluginCustomization.ini]
 SWT SessionManagerDBus: Failed to connect to org.gnome.SessionManager: Error spawning command line ?dbus-launch --autolaunch=1e6623461ce74a0e9013cb3192e91ddf --binary-syntax --close-stderr?: Child process exited with code 1
 SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Error spawning command line ?dbus-launch --autolaunch=1e6623461ce74a0e9013cb3192e91ddf --binary-syntax --close-stderr?: Child process exited with code 1
 [ERROR] There are test failures.
 
 Please refer to /home/jenkins/agent/workspace/text-xtend_cd_java11_experiments/org.eclipse.xtend.ide.tests/target/surefire-reports for the individual test results.
 [INFO] 
```

test is green anyway

**Comment by cdietrich** [comment]
xtext-xtend cmd line
` mvn -B -f tycho-pom.xml --update-snapshots -Dmaven.repo.local=/home/jenkins/.m2/repository --fae -Dmaven.test.failure.ignore=true -Declipse.p2.mirrors=false -DJENKINS_URL=https://ci.eclipse.org/xtext/ -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -s /home/jenkins/.m2/settings.xml -Platest`
xtext-eclipse cmd line
`Calling Maven with ARGS: --batch-mode --update-snapshots --fae -Dmaven.test.failure.ignore=true -Declipse.p2.mirrors=false -Dtycho.disableP2Mirrors=true -DJENKINS_URL=https://ci.eclipse.org/xtext/ -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=info -s /home/jenkins/.m2/settings.xml -Dmaven.repo.local=$VALUE -Platest`

**Comment by cdietrich** [comment]
looks like eclipse fails only for

```
Recording test results
 No test report files were found. Configuration error?
 Error when executing always post condition:
 hudson.AbortException: No test report files were found. Configuration error?
 	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)
 	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:118)
 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3069)
 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
 	at hudson.remoting.Request$2.run(Request.java:369)
 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
 	at java.util.concurrent.FutureTask.run(Unknown Source)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
 	at hudson.remoting.Engine$1$$Lambda$4/000000004401EDD0.run(Unknown Source)
 	at java.lang.Thread.run(Unknown Source)
 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.128.12.1/10.128.12.1:51262
 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
 		at hudson.remoting.Channel.call(Channel.java:998)
 		at hudson.FilePath.act(FilePath.java:1069)
 		at hudson.FilePath.act(FilePath.java:1058)
 		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
 		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
 		at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
 		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:52)
 		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:25)
 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$474/00000000E4091DA0.run(Unknown Source)
 		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
 		at java.util.concurrent.FutureTask.run(Unknown Source)
 		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 		... 1 more
```

as xtend find stuff for gradle and maven-maven it wont fail

**Comment by cdietrich** [comment]
problems seems to be back

**Comment by cdietrich** [comment]
same problem here: https://ci.eclipse.org/xtext/job/xtext-eclipse/job/cd_issue1511/5/console

**Comment by cdietrich** [comment]
can no longer reproduce
