### ISSUE TITLE
SaveWithReconciliationQueuedBuildDataTest.renameSecondaryTopLevelType() hangs with latest jdt

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1135]
SaveWithReconciliationQueuedBuildDataTest.renameSecondaryTopLevelType() hangs with latest jdt

```
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension.waitForElementChangedEvent(JavaEditorExtension.java:138)
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension.waitForPostReconcileEvent(JavaEditorExtension.java:105)
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension.reconcile(JavaEditorExtension.java:60)
	at org.eclipse.xtend.ide.tests.builder.SaveWithReconciliationQueuedBuildDataTest.lambda$0(SaveWithReconciliationQueuedBuildDataTest.java:23)
	at org.eclipse.xtend.ide.tests.builder.SaveWithReconciliationQueuedBuildDataTest$$Lambda$885/0x000000080112c440.apply(Unknown Source)
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension.lambda$2(JavaEditorExtension.java:75)
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension$$Lambda$886/0x000000080112b840.apply(Unknown Source)
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension.waitForElementChangedEvent(JavaEditorExtension.java:137)
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension.waitForPostChangeEvent(JavaEditorExtension.java:109)
	at org.eclipse.xtend.ide.tests.builder.JavaEditorExtension.save(JavaEditorExtension.java:79)
	at org.eclipse.xtend.ide.tests.builder.SaveWithReconciliationQueuedBuildDataTest.doSave(SaveWithReconciliationQueuedBuildDataTest.java:25)
	at org.eclipse.xtend.ide.tests.builder.AbstractSingleEditorQueuedBuildTest.save(AbstractSingleEditorQueuedBuildTest.java:1115)
	at org.eclipse.xtend.ide.tests.builder.AbstractSingleEditorQueuedBuildTest.lambda$10(AbstractSingleEditorQueuedBuildTest.java:242)
	at org.eclipse.xtend.ide.tests.builder.AbstractSingleEditorQueuedBuildTest$$Lambda$707/0x0000000800fa3840.apply(Unknown Source)
	at org.eclipse.xtend.ide.tests.builder.AbstractQueuedBuildDataTest.assertDeltas(AbstractQueuedBuildDataTest.java:209)
	at org.eclipse.xtend.ide.tests.builder.AbstractQueuedBuildDataTest.assertThereAreDeltas(AbstractQueuedBuildDataTest.java:92)
	at org.eclipse.xtend.ide.tests.builder.AbstractSingleEditorQueuedBuildTest.renameSecondaryTopLevelType(AbstractSingleEditorQueuedBuildTest.java:244)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.8/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.8/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.8/DelegatingMethodAccessorImpl.java:43)
```

wonder which platform/jdt changes could have cause that.

**Comment by cdietrich** [comment]
@iloveeclipse any idea?
looks like we dont get a changed event anymore

```
				package mypackage;
				
				public class Bar {
				}
				
				class Bar2 {
				}
```

test renames Bar2 to Bar3

**Comment by cdietrich** [comment]
have no idea why this was working this morning.
maybe luck?!?

**Comment by cdietrich** [comment]
we are waiting for a POST_CHANGE and a POST_RECONCILE event, but we get POST_RECONCILE only

**Comment by iloveeclipse** [comment]
Not sure I can follow last comment, but if you can reproduce this with plain JDT & simple example (add listener, do printout of event etc), we could try to bisect where it was boken.

**Comment by cdietrich** [comment]
i have no idea what this test is doing
and c&p it to a jdt consumable for would be 5000 lines

@szarnekow would be nice if you could have a look at the test
i have no idea what it is doing

**Comment by cdietrich** [comment]
hmmm can also be a stupid test order problem
this one does not close welcome page

**Comment by cdietrich** [comment]
it also works when i do add

```
			if (Display.getCurrent() !== null) {
				while (Display.getDefault().readAndDispatch()) {
					// process queued ui events
				}
			}
```
