### ISSUE TITLE
2.11.0 beta2 causes xtext core plugin to crash on IDEA

### ISSUE THREAD

**Issue by Treverix** [eclipse/xtext-xtend#114]
I've build xtext-idea 2.11.0-beta2 and xtext-xtend 2.11.0-beta2 and installed both on intellij idea 2016.3.2

IDEA behaves normal with only xtext-idea installed and activated but the xtext plugin throws exceptions after adding xtext-xtend (IDE Fatal errors). This causes IDEA to become unstable until I deactivate the xtend plugin again.

Stacktrace from IDEAs IDE Fatal Errors dialog:

```
java.lang.ArrayIndexOutOfBoundsException: 7432
com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 7432
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.util.$StackTraceElements.forMember(StackTraceElements.java:53)
	at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:712)
	at com.google.inject.internal.Errors.formatSource(Errors.java:678)
	at com.google.inject.internal.Errors.format(Errors.java:555)
	at com.google.inject.CreationException.getMessage(CreationException.java:48)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:191)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:102)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.execution.actions.RunConfigurationProducer.getInstance(RunConfigurationProducer.java:226)
	at com.theoryinpractice.testng.ui.actions.TestNGAddToTestsPatternAction.getPatternBasedProducer(TestNGAddToTestsPatternAction.java:36)
	at com.theoryinpractice.testng.ui.actions.TestNGAddToTestsPatternAction.getPatternBasedProducer(TestNGAddToTestsPatternAction.java:31)
	at com.intellij.execution.actions.AbstractAddToTestsPatternAction.update(AbstractAddToTestsPatternAction.java:91)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:122)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:95)
	at com.intellij.ide.ui.customization.CustomizationUtil$2.invokePopup(CustomizationUtil.java:290)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:48)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:59)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 7432
	at com.google.inject.internal.asm.$ClassReader.readClass(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.accept(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.accept(Unknown Source)
	at com.google.inject.internal.util.$LineNumbers.<init>(LineNumbers.java:62)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:36)
	at com.google.inject.internal.util.$StackTraceElements$1.apply(StackTraceElements.java:33)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 67 more
```

**Comment by Treverix** [comment]
There is a hint on SO where they recommend to upgrade to guice 4 to get better error message (they say, the aforementioned exceptions are most probably related to java 8 and lambdas in combination with an improper guice configuration, see: http://stackoverflow.com/a/28249835/105224)

For a quick test, I replaced guice-3.jar with guice-4.1.jar directly on the xtext-xtend plugin and got different exceptions, at least readable ones. 

```
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, org.eclipse.emf.common.util.WrappedException: java.lang.RuntimeException: Cannot create a resource for 'classpath:/org/eclipse/xtend/core/Xtend.xtextbin'; a registered resource factory is needed
  at org.eclipse.xtext.xbase.services.XtypeGrammarAccess.<init>(XtypeGrammarAccess.java:728)
  at org.eclipse.xtext.xbase.services.XtypeGrammarAccess.class(XtypeGrammarAccess.java:728)
  while locating org.eclipse.xtext.xbase.services.XtypeGrammarAccess
    for the 2nd parameter of org.eclipse.xtext.xbase.services.XbaseGrammarAccess.<init>(XbaseGrammarAccess.java:3354)

```

(for the full stack traces, please see the attached idea.log)

[idea.log.zip](https://github.com/eclipse/xtext-xtend/files/691434/idea.log.zip)

**Comment by svenefftinge** [comment]
The error says, that the `BinaryGrammarResourceFactoryImpl` wasn't registered.
Something like this needs to be executed before
```
Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("xtextbin", new BinaryGrammarResourceFactoryImpl());
```

It is usually done as part of the standalone setup.

**Comment by Treverix** [comment]
Unfortunately, still the same with release_2.11.0 - I've just build xtext-xtend and xtext-idea locally, installed the zips and still get the AIOOB exceptions.

Looks like I have to wait for the official idea plugins.
