### ISSUE TITLE
Xtend Activator Problem

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#1143]
After updating to Xtend 2.24.0.v20201123-0220, I observe a problem with the Xtend Activator:

![screencast](https://user-images.githubusercontent.com/20393472/99933206-a3012580-2d5a-11eb-94be-2be1d1318157.gif)

**Environment:**
Eclipse IDE 2020-06 (4.16.0)
Eclipse Xtext 2.24.0.v20201123-0220
Eclipse Xtend 2.24.0.v20201123-0220

**Hint:**
It was working till Xtend 2.24.0.v20201120-0220, so the problem could be related to the [last change](https://github.com/eclipse/xtext-xtend/commit/45aa82b252859db51c3e1bb3cc2f3ea45650bbc0) on the Xtend Activator.

@cdietrich @kthoms Can you reproduce the problem on your computer?

**Comment by cdietrich** [comment]
Please do start the bundle via Osgi console and Post error Message

**Comment by cdietrich** [comment]
and no i cant. but i head problems with xtend classpath container yesterday which somehow resolved magically by restarting

**Comment by miklossy** [comment]
I also observe some problem with the Xtend classpaht container. Unfortunately, they does not disapper by restarting:
![screenshot](https://user-images.githubusercontent.com/20393472/99936908-98e42480-2d64-11eb-9914-69fd70cc9672.png)

**Comment by miklossy** [comment]
> 
> 
> Please do start the bundle via Osgi console and Post error Message
```

osgi> start 2897
org.osgi.framework.BundleException: Error loading bundle activator. org.eclipse.xtend.ide_2.24.0.v20201122-0706 [2897]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:786)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1015)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:439)
	at org.apache.felix.gogo.command.Basic.start(Basic.java:739)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:139)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:91)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415)
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416)
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229)
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.xtend.ide (2897).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:571)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:477)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:620)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:923)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.jdt.core.JavaCore.computeClasspathContainerInitializer(JavaCore.java:3799)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainerInitializer(JavaCore.java:3775)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3176)
	at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:3079)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3141)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2111)
	at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4541)
	at org.eclipse.jdt.internal.ui.InitializeAfterLoadJob$RealJob.run(InitializeAfterLoadJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.xtend.ide.XtendActivator.start() of bundle org.eclipse.xtend.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:864)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1015)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:493)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 22 more
Caused by: java.lang.NullPointerException
	at org.eclipse.xtend.ide.XtendActivator.lambda$0(XtendActivator.java:37)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.eclipse.xtend.ide.XtendActivator.start(XtendActivator.java:34)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:843)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:835)
	... 29 more
java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.xtend.ide (2897).
```

**Comment by cdietrich** [comment]
meh. of course this one does not print which class is not found :(
which eclipse version do you use?

**Comment by miklossy** [comment]
I use Eclipse IDE 2020-06 (4.16.0). There is an NPE in the stacktrace:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.xtend.ide.XtendActivator.lambda$0(XtendActivator.java:37)
```

The problem could be related to the new code in the Xtend Activator introduced 3 days ago:

```
			Display.getCurrent().asyncExec(() -> 
				themeManager.handleEvent(new Event(IThemeEngine.Events.THEME_CHANGED, emptyMap()))
			);
```

https://github.com/eclipse/xtext-xtend/blob/45aa82b252859db51c3e1bb3cc2f3ea45650bbc0/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java#L37-L39

**Comment by cdietrich** [comment]
yes. there are also other problem with that change
https://bugs.eclipse.org/bugs/show_bug.cgi?id=568990

**Comment by kthoms** [comment]
I just installed 2.24.0.v20201123-0220	org.eclipse.xtend.sdk on a fresh 4.17 and did not have a problem

**Comment by cdietrich** [comment]
i see this in my dev env too.

**Comment by cdietrich** [comment]
looks like it depends if xtend is already activated somewhere es or not

**Comment by cdietrich** [comment]
```
java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.xtend.ide (5340).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:477)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:616)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:923)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.jdt.core.JavaCore.computeClasspathContainerInitializer(JavaCore.java:3805)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainerInitializer(JavaCore.java:3781)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3176)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2116)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3758)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3196)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3360)
	at org.eclipse.jdt.internal.core.ClasspathChange.generateDelta(ClasspathChange.java:243)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2127)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:477)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:195)
	at org.eclipse.core.internal.resources.SavedState.processResourceChangeEvents(SavedState.java:84)
	at org.eclipse.jdt.internal.core.JavaModelManager$20$1.run(JavaModelManager.java:5416)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2312)
	at org.eclipse.jdt.internal.core.JavaModelManager$20.run(JavaModelManager.java:5407)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

this is definitely not an ui thread
so display.getcurrent will be null

**Comment by kthoms** [comment]
Ok, this explains it. Anyway, on [bug#568990](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568990) we got the hint to try to register a property change listener. I'll explore that now.

**Comment by kthoms** [comment]
The initial application of the syntax coloring preferences has to happen, and it has to run on the UI thread. So instead of Display#getCurrent we might have to use Display#getDefault? Or how could we enforce that this is executed when UI is available?

**Comment by cdietrich** [comment]
am not sure about that. lets discuss in call

**Comment by kthoms** [comment]
In `org.eclipse.debug.internal.ui.DebugUIPlugin` they use 
```
PlatformUI.getWorkbench().getDisplay()
```
to register a theme listener

**Comment by cdietrich** [comment]
we should also check egit what they do

**Comment by kthoms** [comment]
We decided to deactivate the new theme manager for this release and investigate the dark theme for 2.25 again.
