### ISSUE TITLE
Fix Bug464136Test

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-xtend#123]
After switching to run tests in the Gradle build, Bug464136Test fails:
```
org.junit.ComparisonFailure: expected:<...136Processor.lambda$[]0(Bug464136Processor...> but was:<...136Processor.lambda$[doTransform$]0(Bug464136Processor...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.xtend.core.tests.macro.Bug464136Test.lambda$testThrownErrorInPreValidation$1(Bug464136Test.java:43)
	at org.eclipse.xtend.core.compiler.batch.XtendCompilerTester$1.accept(XtendCompilerTester.java:90)
	at org.eclipse.xtend.core.compiler.batch.XtendCompilerTester$1.accept(XtendCompilerTester.java:87)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper.compile(CompilationTestHelper.java:245)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper.compile(CompilationTestHelper.java:194)
	at org.eclipse.xtend.core.compiler.batch.XtendCompilerTester.compile(XtendCompilerTester.java:87)
	at org.eclipse.xtend.core.tests.macro.Bug464136Test.testThrownErrorInPreValidation(Bug464136Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cdietrich** [comment]
this can be reproduced with a plain gralde project and this unit test as well

```
package demox;

import static org.junit.Assert.*;

import java.util.function.Supplier;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		final Supplier<String> _function = () -> {
			throw new IllegalStateException();
		};
		try {
			_function.get();
		} catch (IllegalStateException e) {
			StackTraceElement[] stackTrace = e.getStackTrace();
			assertEquals("demox.LibraryTest.lambda$0(LibraryTest.java:16)",stackTrace[0].toString());
		}
		
	}
}

```

**Comment by cdietrich** [comment]
@spoenemann @svenefftinge 

since this seems a eclipsec vs javac problem: how shall we deal with it?

**Comment by cdietrich** [comment]
maybe we could turn the assertion into an "or" of both cases?

**Comment by spoenemann** [comment]
> maybe we could turn the assertion into an "or" of both cases?

If eclipsec vs javac is really the cause of the problem, that would be a good solution.
