### ISSUE TITLE
RenameStrategyTest fails on latest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1285]
RenameStrategyTest fails on latest

https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_testTycho30/3/consoleFull
https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_testTycho30/2/consoleFull

```
java.lang.AssertionError
	at org.eclipse.xtend.ide.tests.refactoring.RenameStrategyTest.testOverrideIndicatorAnnotationAfterFileRename(RenameStrategyTest.java:102)
```
@szarnekow  do you have any platform / jdt changes in mind that could cause that.

**Comment by cdietrich** [comment]
cc @iloveeclipse maybe you have an idea too

**Comment by cdietrich** [comment]
am not sure if no build is happening or job that updates the annotation not running

**Comment by cdietrich** [comment]
@szarnekow somehow the model listener for the document is not called

**Comment by iloveeclipse** [comment]
@cdietrich : do the test checks **decorations** existence on some object in an explorer? 
If yes, it should do some more async waits on UI thread. See [bug 450663](https://bugs.eclipse.org/bugs/show_bug.cgi?id=450663)

**Comment by cdietrich** [comment]
no, i am currently debugging . problem may be arround setInput

**Comment by iloveeclipse** [comment]
Can you add link to the test code that fails?

**Comment by cdietrich** [comment]
am not sure if it helps. it is internal xtext listener that no longer run.
problem is in the platform i-build of today. this morning it was still running

**Comment by cdietrich** [comment]
its actually a swollen exception
class not found exception org.eclipse.ui.part.FileEditorInput
```
EquinoxClassLoader(ClassLoader).loadClass(String) line: 522	
XbaseDocumentProvider(FileDocumentProvider).handleElementMoved(IFileEditorInput, IPath) line: 826	
FileDocumentProvider$FileSynchronizer$3.execute(IFileEditorInput) line: 265	
FileDocumentProvider$FileSynchronizer$3(FileDocumentProvider$SafeChange).run() line: 143	
RunnableLock.run(Display) line: 40	
UISynchronizer(Synchronizer).runAsyncMessages(boolean) line: 185	
Display.runAsyncMessages(boolean) line: 5101	
Display.readAndDispatch() line: 4584	
RenameStrategyTest.sleepWhile(Predicate<T>, Provider<T>, long) line: 110	
RenameStrategyTest.testOverrideIndicatorAnnotationAfterFileRename() line: 92	

```

**Comment by iloveeclipse** [comment]
Is this a maven/tycho build, that grabs some random bundles based on manifest versions? Could be someone forgot to bump lover range for required bundle version in code that needs that?

**Comment by cdietrich** [comment]
no it takes lastest greates and i see it on ci.eclipse.org and local.

**Comment by cdietrich** [comment]
on my mac where it works i have org.eclipse.ui.ide_3.18.500.v20220124-1108.jar
on linux where it does not

**Comment by iloveeclipse** [comment]
But org.eclipse.ui.ide is on classpath of Xtext code??? Any errors **before** the class loading error?

**Comment by cdietrich** [comment]
no erros

**Comment by iloveeclipse** [comment]
org.eclipse.ui.editors "expects" very old minimal bundle versions from everything. Are you sure **right** org.eclipse.ui.ide is there?

**Comment by cdietrich** [comment]
what is the right? we just use https://download.eclipse.org/eclipse/updates/4.23-I-builds/

**Comment by cdietrich** [comment]
@iloveeclipse
with sources i get proper exception
```
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalArgumentException
	at org.eclipse.core.runtime.ListenerList.remove(ListenerList.java:220)
	at org.eclipse.debug.core.DebugPlugin.removeDebugEventListener(DebugPlugin.java:685)
	at org.eclipse.debug.internal.ui.codemining.DebugValueCodeMiningProvider.dispose(DebugValueCodeMiningProvider.java:87)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.setCodeMiningProviders(CodeMiningManager.java:101)
	at org.eclipse.jface.text.source.SourceViewer.setCodeMiningProviders(SourceViewer.java:1274)
	at org.eclipse.ui.texteditor.AbstractTextEditor.installCodeMiningProviders(AbstractTextEditor.java:4016)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:4005)
	at org.eclipse.ui.texteditor.AbstractTextEditor.doSetInput(AbstractTextEditor.java:4176)
	at org.eclipse.ui.texteditor.StatusTextEditor.doSetInput(StatusTextEditor.java:262)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.doSetInput(AbstractDecoratedTextEditor.java:1479)
	at org.eclipse.ui.editors.text.TextEditor.doSetInput(TextEditor.java:153)
	at org.eclipse.xtext.ui.editor.XtextEditor.doSetInput(XtextEditor.java:261)
	at org.eclipse.xtext.xbase.ui.editor.XbaseEditor.doSetInput(XbaseEditor.java:123)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setInputWithNotify(AbstractTextEditor.java:4232)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setInput(AbstractTextEditor.java:4252)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener$1.run(AbstractTextEditor.java:529)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener.execute(AbstractTextEditor.java:590)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener.elementMoved(AbstractTextEditor.java:557)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider.fireElementMoved(AbstractDocumentProvider.java:724)
	at org.eclipse.ui.editors.text.FileDocumentProvider.handleElementMoved(FileDocumentProvider.java:826)
	at org.eclipse.ui.editors.text.FileDocumentProvider$FileSynchronizer$3.execute(FileDocumentProvider.java:265)
```

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=507546

**Comment by iloveeclipse** [comment]
I've just pushed a patch, found it differently - jenkins fails for JDT UI now :-(

**Comment by cdietrich** [comment]
Upstream Patch in platform solves it.
