### ISSUE TITLE
X2J making more problems on J17

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1382]
protected def provideCustomEnvironment(ASTParser parser) {
		val String[] cpEntries = classpathScanner.getSystemClasspath()
		parser.setEnvironment(cpEntries, null, null, true)
	}

in ASTParserFactory makes problems on modular paths with latest platform

```
Failed to init Classpath for jar file /java.base
java.nio.file.NoSuchFileException: /java.base
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
    at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
    at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
    at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:204)
    at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
    at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:285)
    at org.eclipse.jdt.core.dom.NameEnvironmentWithProgress.<init>(NameEnvironmentWithProgress.java:36)
    at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:771)
    at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1245)
    at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
    at org.eclipse.xtend.core.javaconverter.ASTParserFactory$ASTParserWrapper.createAST(ASTParserFactory.java:34)
```

**Comment by cdietrich** [comment]
@szarnekow any idea?

**Comment by cdietrich** [comment]
move to 2.30, likely wont fix

**Comment by cdietrich** [comment]
wont fix
