### ISSUE TITLE
Active annotation at method parameter leads to ClassCastException

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-xtend#171]
This seems to be a regression in Xtend 2.11.0 (or earlier) as it should have been fixed in 2013: https://bugs.eclipse.org/bugs/show_bug.cgi?id=404161

Annotating a method parameter with an active annotation leads to a ClassCastException in the annotation processor:

<pre>
java.lang.ClassCastException: org.eclipse.xtend.core.xtend.impl.XtendParameterImpl cannot be cast to org.eclipse.xtend.core.xtend.XtendMember
	at org.eclipse.xtend.core.macro.AnnotationProcessor.lambda$null$0(AnnotationProcessor.java:145)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.head(IteratorExtensions.java:140)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.head(IterableExtensions.java:119)
	at MyParameterProcessor.doRegisterGlobals(AbstractParameterProcessor.java:40)
	at org.eclipse.xtend.core.macro.AnnotationProcessor.lambda$indexingPhase$1(AnnotationProcessor.java:147)
	at org.eclipse.xtend.core.macro.AnnotationProcessor.runWithCancelIndiciator(AnnotationProcessor.java:278)
	at org.eclipse.xtend.core.macro.AnnotationProcessor.indexingPhase(AnnotationProcessor.java:149)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.infer(XtendJvmModelInferrer.java:196)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:382)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareBatchTypeResolver.getEntryPoints(LogicalContainerAwareBatchTypeResolver.java:44)
	at org.eclipse.xtend.core.typesystem.TypeDeclarationAwareBatchTypeResolver.getEntryPoints(TypeDeclarationAwareBatchTypeResolver.java:56)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver.getTypeResolver(DefaultBatchTypeResolver.java:84)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:49)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:46)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:46)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:71)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:165)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper$Result.doLinking(CompilationTestHelper.java:507)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper$Result.doValidation(CompilationTestHelper.java:513)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper$Result.doGenerate(CompilationTestHelper.java:530)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper.compile(CompilationTestHelper.java:245)
	at org.eclipse.xtext.xbase.testing.CompilationTestHelper.compile(CompilationTestHelper.java:195)
	at org.eclipse.xtend.core.compiler.batch.XtendCompilerTester.compile(XtendCompilerTester.java:87)
	at IterableDataProvidedByProcessorTest.testValidIterableSubtypeInternal(IterableDataProvidedByProcessorTest.java:950)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
</pre>

**Comment by OLibutzki** [comment]
In the inferencePhase and validationPhase a switch checks for XtendMember and XtendParameter. In the indexingPhase there is a cast to XtendMember without a type check.

**Comment by cdietrich** [comment]
fixed in 2.12
