### ISSUE TITLE
IAE in XtendHighlightingCalculator

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#184]
```
class Demo {
	
	def xxxx() {
		'''
		TODO i am no todo
		«««		TODO xxxxxxx
lala TODO i am no todo
«««		TODO2 xxxxxxx22
lala TODO i am no todo
		'''
	}
	
}
```

gives

```
java.lang.IllegalArgumentException: length -2 is < 0
	at org.eclipse.xtext.util.TextRegion.<init>(TextRegion.java:20)
	at org.eclipse.xtend.ide.common.highlighting.XtendHighlightingCalculator$RichStringHighlighter.resetCurrentOffset(XtendHighlightingCalculator.java:330)
	at org.eclipse.xtend.ide.common.highlighting.XtendHighlightingCalculator$RichStringHighlighter.announceNextLiteral(XtendHighlightingCalculator.java:303)
	at org.eclipse.xtend.core.richstring.RichStringProcessor$Implementation.caseLiteral(RichStringProcessor.java:337)
	at org.eclipse.xtend.core.richstring.RichStringProcessor$Implementation.caseLiteral(RichStringProcessor.java:1)
	at org.eclipse.xtend.core.richstring.util.ProcessedRichStringSwitch.doSwitch(ProcessedRichStringSwitch.java:104)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.xtend.core.richstring.RichStringProcessor$Implementation.doSwitch(RichStringProcessor.java:196)
	at org.eclipse.xtend.core.richstring.RichStringProcessor$Implementation.caseProcessedRichString(RichStringProcessor.java:215)
	at org.eclipse.xtend.core.richstring.RichStringProcessor$Implementation.caseProcessedRichString(RichStringProcessor.java:1)
	at org.eclipse.xtend.core.richstring.util.ProcessedRichStringSwitch.doSwitch(ProcessedRichStringSwitch.java:83)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.xtend.core.richstring.RichStringProcessor$Implementation.doSwitch(RichStringProcessor.java:196)
	at org.eclipse.xtend.core.richstring.RichStringProcessor.process(RichStringProcessor.java:34)
	at org.eclipse.xtend.ide.common.highlighting.XtendHighlightingCalculator.highlightRichStrings(XtendHighlightingCalculator.java:267)
	at org.eclipse.xtend.ide.common.highlighting.XtendHighlightingCalculator.highlightElement(XtendHighlightingCalculator.java:196)
	at org.eclipse.xtend.ide.common.highlighting.XtendHighlightingCalculator.highlightElement(XtendHighlightingCalculator.java:148)
	at org.eclipse.xtext.ide.editor.syntaxcoloring.DefaultSemanticHighlightingCalculator.highlightElementRecursively(DefaultSemanticHighlightingCalculator.java:87)
	at org.eclipse.xtext.ide.editor.syntaxcoloring.DefaultSemanticHighlightingCalculator.searchAndHighlightElements(DefaultSemanticHighlightingCalculator.java:79)
	at org.eclipse.xtext.ide.editor.syntaxcoloring.DefaultSemanticHighlightingCalculator.doProvideHighlightingFor(DefaultSemanticHighlightingCalculator.java:69)
	at org.eclipse.xtext.xbase.ide.highlighting.XbaseHighlightingCalculator.doProvideHighlightingFor(XbaseHighlightingCalculator.java:124)
	at org.eclipse.xtext.xbase.ide.highlighting.XbaseHighlightingCalculator.provideHighlightingFor(XbaseHighlightingCalculator.java:113)
	at org.eclipse.xtext.ide.editor.syntaxcoloring.MergingHighlightedPositionAcceptor.provideHighlightingFor(MergingHighlightedPositionAcceptor.java:63)
	at org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler.reconcilePositions(HighlightingReconciler.java:151)
	at org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler.modelChanged(HighlightingReconciler.java:402)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.notifyModelListeners(XtextDocument.java:215)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:444)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by cdietrich** [comment]
fixed in 2.12
