### ISSUE TITLE
NPE in DebugSourceInstallingCompilationParticipant

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#21]
```
!ENTRY org.apache.log4j 4 0 2016-08-01 07:50:55.362
!MESSAGE org.eclipse.xtext.builder.smap.DebugSourceInstallingCompilationParticipant  - Could not process /Abc/xtend-gen/abc/Abc.java to install source information: null

!STACK 0
java.lang.NullPointerException
	at org.eclipse.xtext.builder.smap.DebugSourceInstallingCompilationParticipant.buildFinished(DebugSourceInstallingCompilationParticipant.java:145)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:235)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by cdietrich** [comment]
@svenefftinge @meysholdt should we restore the usage of smap?
if yes do you know why the manifest of org.eclipse.xtext.smap misses log4j?
