### ISSUE TITLE
Anonymous subclass lead to duplicate classes in generated Java code

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/xtext-xtend#243]
The Xtend code
```
class A {
	val x = new A(null) {
		val y = null
	}
	
	new(Object o) {
	}
}

```
is generated to
```
package com.bosch.aeeit.p42.views.compare;

import org.eclipse.xtext.xbase.lib.Functions.Function0;

@SuppressWarnings("all")
public class A {
  private final A x = new Function0<A>() {
    public A apply() {
      abstract class __A_1 extends A {
        __A_1(final Object o) {
          super(o);
        }
        
        Object y;
      }
      
      abstract class __A_1 extends A {
        __A_1(final Object o) {
          super(o);
        }
        
        Object y;
      }
      
      __A_1 ___A_1 = new __A_1(null) {
        {
          y = null;
        }
      };
      return ___A_1;
    }
  }.apply();
  
  public A(final Object o) {
  }
}
```

This seems to happen, if the called constructor requires a parameter _and_ the anonymous subtypes adds an additional method or field, like `y` in the above example.
The super type of the anonymous type can be any regular class or inner class - I chose `A` here just for the brevity of the example.

**Comment by cdietrich** [comment]
here are the paths that lead to the generation beeing done twice

```
	at org.eclipse.xtend.core.compiler.XtendGenerator.compileLocalTypeStubs(XtendGenerator.java:262)
	at org.eclipse.xtend.core.compiler.XtendCompiler.prependLocalTypesIfFieldInitializer(XtendCompiler.java:374)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:361)
```

```
	at org.eclipse.xtend.core.compiler.XtendGenerator.compileLocalTypeStubs(XtendGenerator.java:262)
	at org.eclipse.xtend.core.compiler.XtendCompiler.prependLocalTypesIfFieldInitializer(XtendCompiler.java:374)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:361)
```

once for the null literal, once for the Anonymous class
