### ISSUE TITLE
Method call argument evaluation order incorrect

### ISSUE THREAD

**Issue by djozis** [eclipse/xtext-xtend#347]
Arguments don't evaluate from left to right in some scenarios.
Example:
```
class Order {
    static val array = newIntArrayOfSize(1)
    static var index = 0

    def static void main(String[] args) {
        array.set(index, index++)
    }
}
```
Compiles to:
```
@SuppressWarnings("all")
public class Order {
  private final static int[] array = new int[1];
  
  private static int index = 0;
  
  public static void main(final String[] args) {
    int _plusPlus = Order.index++;
    Order.array[Order.index] = _plusPlus;
  }
}
```
As a result, behaves incorrectly:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at Order.main(Order.java:11)
```

**Comment by djozis** [comment]
Just to clarify ambiguity, this has nothing to do with calling a method annotated with Inline:
```
class Order {
    static val list = new ArrayList<Integer>(#[0])
    static var index = 0

    def static void main(String[] args) {
        list.set(index, index++)
    }
}
```
Compiles to
```
@SuppressWarnings("all")
public class Order {
  private final static ArrayList<Integer> list = new ArrayList<Integer>(Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(0))));
  
  private static int index = 0;
  
  public static void main(final String[] args) {
    int _plusPlus = Order.index++;
    Order.list.set(Order.index, Integer.valueOf(_plusPlus));
  }
}
```
Results in
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.set(Unknown Source)
	at Order.main(Order.java:15)
```

**Comment by cdietrich** [comment]
@szarnekow shouldnt we either create vars for everything or for nothing?

**Comment by cdietrich** [comment]
or do we consider that a "design" flaw?
