### ISSUE TITLE
Bogus behaviour when enabling resource clustering

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#378]
```
1288 [Worker-0: Building workspace] ERROR org.eclipse.xtext.builder.ParallelBuilderParticipant$Tripwire  - Removed adapter to resource set during code generation: org.eclipse.xtext.resource.CompilerPhases$IndexingAdapter@4cca8af4
java.lang.IllegalStateException: Removed adapter to resource set during code generation: org.eclipse.xtext.resource.CompilerPhases$IndexingAdapter@4cca8af4
	at org.eclipse.xtext.builder.ParallelBuilderParticipant$Tripwire.removed(ParallelBuilderParticipant.java:156)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl$EAdapterList.didRemove(BasicNotifierImpl.java:131)
	at org.eclipse.emf.common.util.BasicEList.remove(BasicEList.java:615)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl$EAdapterList.remove(BasicNotifierImpl.java:221)
	at org.eclipse.emf.common.util.AbstractEList.remove(AbstractEList.java:456)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl$EAdapterList.remove(BasicNotifierImpl.java:214)
	at org.eclipse.xtext.resource.CompilerPhases.setIndexing(CompilerPhases.java:35)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.infer(XtendJvmModelInferrer.java:207)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:382)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareBatchTypeResolver.getEntryPoints(LogicalContainerAwareBatchTypeResolver.java:44)
	at org.eclipse.xtend.core.typesystem.TypeDeclarationAwareBatchTypeResolver.getEntryPoints(TypeDeclarationAwareBatchTypeResolver.java:56)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver.getTypeResolver(DefaultBatchTypeResolver.java:84)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:49)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:46)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:71)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:165)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:500)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.resolveProxies(ResourceValidatorImpl.java:161)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:74)
	at org.eclipse.xtend.core.validation.CachingResourceValidatorImpl.lambda$0(CachingResourceValidatorImpl.java:70)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtend.core.validation.CachingResourceValidatorImpl.validate(CachingResourceValidatorImpl.java:72)
	at org.eclipse.xtend.ide.validator.XtendResourceValidator.validate(XtendResourceValidator.java:31)
	at org.eclipse.xtext.xbase.compiler.ElementIssueProvider$Factory.collectIssues(ElementIssueProvider.java:95)
	at org.eclipse.xtext.xbase.compiler.ElementIssueProvider$Factory.attachData(ElementIssueProvider.java:79)
	at org.eclipse.xtend.core.compiler.XtendGenerator.beforeGenerate(XtendGenerator.java:101)
	at org.eclipse.xtext.generator.GeneratorDelegate.beforeGenerate(GeneratorDelegate.java:52)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.createRunnable(ParallelBuilderParticipant.java:295)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doBuild(ParallelBuilderParticipant.java:219)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:263)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:292)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:323)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:156)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

```
java.lang.IllegalStateException: Added adapter to resource set during code generation: org.eclipse.xtext.resource.CompilerPhases$IndexingAdapter@6144c05c
	at org.eclipse.xtext.builder.ParallelBuilderParticipant$Tripwire.added(ParallelBuilderParticipant.java:149)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl$EAdapterList.didAdd(BasicNotifierImpl.java:118)
	at org.eclipse.emf.common.util.BasicEList.addUnique(BasicEList.java:418)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl$EAdapterList.add(BasicNotifierImpl.java:193)
	at org.eclipse.xtext.resource.CompilerPhases.setIndexing(CompilerPhases.java:33)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.infer(XtendJvmModelInferrer.java:185)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:382)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareBatchTypeResolver.getEntryPoints(LogicalContainerAwareBatchTypeResolver.java:44)
	at org.eclipse.xtend.core.typesystem.TypeDeclarationAwareBatchTypeResolver.getEntryPoints(TypeDeclarationAwareBatchTypeResolver.java:56)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver.getTypeResolver(DefaultBatchTypeResolver.java:84)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:49)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:46)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:71)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:165)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:500)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.resolveProxies(ResourceValidatorImpl.java:161)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:74)
	at org.eclipse.xtend.core.validation.CachingResourceValidatorImpl.lambda$0(CachingResourceValidatorImpl.java:70)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtend.core.validation.CachingResourceValidatorImpl.validate(CachingResourceValidatorImpl.java:72)
	at org.eclipse.xtend.ide.validator.XtendResourceValidator.validate(XtendResourceValidator.java:31)
	at org.eclipse.xtext.xbase.compiler.ElementIssueProvider$Factory.collectIssues(ElementIssueProvider.java:95)
	at org.eclipse.xtext.xbase.compiler.ElementIssueProvider$Factory.attachData(ElementIssueProvider.java:79)
	at org.eclipse.xtend.core.compiler.XtendGenerator.beforeGenerate(XtendGenerator.java:101)
	at org.eclipse.xtext.generator.GeneratorDelegate.beforeGenerate(GeneratorDelegate.java:52)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.createRunnable(ParallelBuilderParticipant.java:295)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doBuild(ParallelBuilderParticipant.java:219)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:263)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:292)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:268)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:162)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

```

**Comment by cdietrich** [comment]
unfortunately i cannot reproduce this reliably

**Comment by cdietrich** [comment]
can reproduce it with this policy

```
@Override
	public boolean continueProcessing(ResourceSet resourceSet, URI next, int alreadyProcessed) {
		boolean b = alreadyProcessed<1;
		return b;
	}
```

**Comment by cdietrich** [comment]
@szarnekow any ideas? just found this during playing around. neither in my project nor in default shipment we use xtend with clustering

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
