### ISSUE TITLE
SWTBot Tests Fail

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#379]
``` 
java.lang.ExceptionInInitializerError: null
	at org.eclipse.swtbot.swt.finder.keyboard.KeyboardLayout.getKeyboardLayout(KeyboardLayout.java:89)
	at org.eclipse.swtbot.swt.finder.keyboard.KeyboardLayout.getDefaultKeyboardLayout(KeyboardLayout.java:75)
	at org.eclipse.swtbot.swt.finder.keyboard.Keystrokes.<clinit>(Keystrokes.java:110)
	at org.eclipse.swtbot.swt.finder.keyboard.Keyboard.typeCharacter(Keyboard.java:100)
	at org.eclipse.swtbot.swt.finder.keyboard.Keyboard.typeText(Keyboard.java:89)
	at org.eclipse.swtbot.swt.finder.keyboard.Keyboard.typeText(Keyboard.java:77)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotStyledText.typeText(SWTBotStyledText.java:227)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotStyledText.typeText(SWTBotStyledText.java:211)
	at org.eclipse.swtbot.eclipse.finder.widgets.SWTBotEclipseEditor.typeText(SWTBotEclipseEditor.java:344)
	at org.eclipse.xtend.ide.tests.AbstractRefactoringSwtBotTest.renameInJavaEditor(AbstractRefactoringSwtBotTest.java:155)
	at org.eclipse.xtend.ide.tests.RenameJavaClassSwtBotTest.renameJavaClass(RenameJavaClassSwtBotTest.java:62)
```

**Comment by cdietrich** [comment]
@meysholdt @spoenemann where the recent changes on the machines.
could be that keyboard layout is no longer found

**Comment by cdietrich** [comment]
could be caused by formatting pom. will try that
