### ISSUE TITLE
RenameJavaClassSwtBotTest fails on Photon

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#381]
```
Timeout after: 5000 ms.: The widget with mnemonic 'Delete' was not enabled.

Stacktrace

org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: The widget with mnemonic 'Delete' was not enabled.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.waitForEnabled(AbstractSWTBot.java:650)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.click(SWTBotMenu.java:68)
	at org.eclipse.xtend.ide.tests.SwtBotProjectHelper.clearSourceFolderContents(SwtBotProjectHelper.java:283)
	at org.eclipse.xtend.ide.tests.SwtBotProjectHelper.clearSourceFolderContents(SwtBotProjectHelper.java:263)
	at org.eclipse.xtend.ide.tests.AbstractRefactoringSwtBotTest.setUp(AbstractRefactoringSwtBotTest.java:88)
```

**Comment by cdietrich** [comment]
JDT behavior has changed. default package can no longer be deleted. created https://bugs.eclipse.org/bugs/show_bug.cgi?id=532245

**Comment by cdietrich** [comment]
JDT considers this as "feature" thus we have to adapt the test.
