### ISSUE TITLE
ClassCastException when applying Quickfix 'Remove the redundant modifier.' 

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#408]
Given is the following Xtend class:
![screenshot](https://user-images.githubusercontent.com/20393472/38163736-256ca434-34f9-11e8-89f5-ae42d58d1d0d.png)

Wenn applying the offered quickfix 'Remove the redundant modifier.' on an extension variable having no name, the following Exception is thrown:
```
org.eclipse.emf.common.util.WrappedException: java.lang.ClassCastException: org.eclipse.xtext.nodemodel.impl.CompositeNode cannot be cast to org.eclipse.xtext.nodemodel.ILeafNode
	at org.eclipse.xtext.ui.editor.quickfix.IssueResolution.apply(IssueResolution.java:78)
	at org.eclipse.xtext.ui.editor.quickfix.QuickAssistCompletionProposal.apply(QuickAssistCompletionProposal.java:36)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:987)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:931)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$11(CompletionProposalPopup.java:927)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$5.widgetDefaultSelected(CompletionProposalPopup.java:672)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:120)
```

**Comment by cdietrich** [comment]
interesting part of the stacktrace

```
Caused by: java.lang.ClassCastException: org.eclipse.xtext.nodemodel.impl.CompositeNode cannot be cast to org.eclipse.xtext.nodemodel.ILeafNode
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:438)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:501)
	at org.eclipse.xtend.core.serializer.AbstractXtendSemanticSequencer.sequence_Member(AbstractXtendSemanticSequencer.java:940)
	at org.eclipse.xtend.core.serializer.AbstractXtendSemanticSequencer.sequence(AbstractXtendSemanticSequencer.java:575)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.ide.serializer.impl.PartialSerializer$SerializeRecursiveStrategy.serialize(PartialSerializer.java:162)
	at org.eclipse.xtext.ide.serializer.impl.PartialSerializer.serializeChanges(PartialSerializer.java:280)
	at org.eclipse.xtext.ide.serializer.impl.RecordingXtextResourceUpdater.applyChange(RecordingXtextResourceUpdater.java:80)
	at org.eclipse.xtext.ide.serializer.impl.ChangeSerializer.endRecordChanges(ChangeSerializer.java:164)
	at org.eclipse.xtext.ide.serializer.impl.ChangeSerializer.applyModifications(ChangeSerializer.java:93)
	at org.eclipse.xtext.ui.editor.model.edit.BatchModification.applyInWorkspace(BatchModification.java:142)
	at org.eclipse.xtext.ui.editor.model.edit.BatchModification$1.execute(BatchModification.java:89)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
	at org.eclipse.xtext.ui.editor.model.edit.BatchModification.apply(BatchModification.java:91)
	at org.eclipse.xtext.ui.editor.model.edit.MultiModificationWrapper.apply(MultiModificationWrapper.java:49)
```

**Comment by cdietrich** [comment]
ti.getNode is a composite node and contains the leading whitespace

@meysholdt any ideas?

**Comment by cdietrich** [comment]
there are more cases not working

```
Caused by: java.lang.RuntimeException: No Context for JvmGenericType.members[2]->JvmOperation.returnType->XComputedTypeReference could be found
	at org.eclipse.xtext.ide.serializer.impl.PartialSerializer.getSerializationContext(PartialSerializer.java:233)
	at org.eclipse.xtext.ide.serializer.impl.PartialSerializer.serializeChanges(PartialSerializer.java:255)
	at org.eclipse.xtext.ide.serializer.impl.RecordingXtextResourceUpdater.applyChange(RecordingXtextResourceUpdater.java:80)
	at org.eclipse.xtext.ide.serializer.impl.ChangeSerializer.endRecordChanges(ChangeSerializer.java:164)
	at org.eclipse.xtext.ide.serializer.impl.ChangeSerializer.applyModifications(ChangeSerializer.java:93)
	at org.eclipse.xtext.ui.editor.model.edit.BatchModification.applyInWorkspace(BatchModification.java:142)
	at org.eclipse.xtext.ui.editor.model.edit.BatchModification$1.execute(BatchModification.java:89)

```

```
import java.text.SimpleDateFormat

class Foo {
	var private SimpleDateFormat DateFormat = new SimpleDateFormat
}
```

**Comment by meysholdt** [comment]
reopen, since https://github.com/eclipse/xtext-core/pull/692 only fixes the CCE.

**Comment by cdietrich** [comment]
@meysholdt what exactly is left open?

**Comment by miklossy** [comment]
I tested the fix today the problem reported here has been solved. I would say that this issue can be closed.

**Comment by cdietrich** [comment]
@meysholdt any updates

**Comment by cdietrich** [comment]
main paintpoint seems still to be that the change serializer does not support derived state properly. thus it is a kind of mixed good idea to have a multi fix here

**Comment by cdietrich** [comment]
@miklossy did you try to change the quickfix not to update references?

e.g.

```
		acceptor.acceptMulti(issue, label, description, image, new ICompositeModification<XtendMember>() {

			@Override
			public void apply(XtendMember element, ICompositeModificationContext<XtendMember> context) {
				context.setUpdateCrossReferences(false);
				context.setUpdateRelatedFiles(false);
				context.addModification(element, new IModificationPart<XtendMember>() {
					@Override
					public void apply(XtendMember element) {
						element.getModifiers().remove(modifier);
					}
				});

			}
		});
```

**Comment by cdietrich** [comment]
@miklossy could you give it a try. i cannot reproduce on my try
