### ISSUE TITLE
How to setup a AA-Test in Xtend 2.14, eclipse or maven, right

### ISSUE THREAD

**Issue by Lexanius** [eclipse/xtext-xtend#456]
Hi

my current Test: 

```
package generator.annotation;

import org.eclipse.xtend.core.compiler.batch.XtendCompilerTester
import org.junit.Test

class ExceptionAnnotationTest {

    extension XtendCompilerTester compile = XtendCompilerTester.newXtendCompilerTester(class.classLoader)

    @Test
    def test() {
        '''
            @ExceptionConstructor
            class IllegalFileCompilation {
            }
            
        '''.assertCompilesTo(
            '''
                import generator.annotation.ExceptionConstructor;
                
                @ExceptionConstructor
                @SuppressWarnings("all")
                public class IllegalFileCompilation extends Exception {
                  public IllegalFileCompilation(final String message) {
                    super(message);
                  }
                  
                  public IllegalFileCompilation(final Throwable cause) {
                    super(cause);
                  }
                  
                  public IllegalFileCompilation(final String message, final Throwable cause) {
                    super(message, cause);
                  }
                  
                  public IllegalFileCompilation(final String message, final Throwable cause, final boolean enableSuppression, final boolean writableStackTrace) {
                    super(message, cause, enableSuppression, writableStackTrace);
                  }
                }
            '''
        )
    }
}
```

throws the Exception on maven and eclipse

```
ExceptionAnnotationTest.test (Failed Tests first)
test(generator.annotation.ExceptionAnnotationTest)
java.lang.NoClassDefFoundError: Lorg/eclipse/xtext/xbase/testing/CompilationTestHelper;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:649)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:967)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1000)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.eclipse.xtend.core.compiler.batch.XtendCompilerTester.newXtendCompilerTester(XtendCompilerTester.java:55)
	at generator.annotation.ExceptionAnnotationTest.<init>(ExceptionAnnotationTest.java:11)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.ClassNotFoundException: org.eclipse.xtext.xbase.testing.CompilationTestHelper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
```

### pom.xml
my maven pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    
	<groupId>generator</groupId>
    <artifactId>xtend-aa-test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <xtend.version>2.14.0</xtend.version>
        <xtext.version>2.14.0</xtext.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.xtend</groupId>
                <artifactId>xtend-maven-plugin</artifactId>
                <version>${xtend.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                            <goal>xtend-install-debug-info</goal>
                            <goal>xtend-test-install-debug-info</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <outputDirectory>${project.build.directory}/xtend-gen/main
                    </outputDirectory>
                    <testOutputDirectory>
                        ${project.build.directory}/xtend-gen/test
                    </testOutputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>

        <!-- Xtends -->
        <dependency>
            <groupId>org.eclipse.xtend</groupId>
            <artifactId>org.eclipse.xtend.lib</artifactId>
            <version>${xtend.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.xtext</groupId>
            <artifactId>org.eclipse.xtext</artifactId>
            <version>${xtext.version}</version>
        </dependency>

        <!-- Tests -->
        <dependency>
            <groupId>org.eclipse.xtend</groupId>
            <artifactId>org.eclipse.xtend.core</artifactId>
            <version>${xtend.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-junit</artifactId>
            <version>2.0.0.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```

### System:

Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: C:\Users\scoop\apps\maven\current
Java version: 1.8.0_172, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_172\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional is to say: 

* `extension XtendCompilerTester compilerTester = XtendCompilerTester.newXtendCompilerTester(Lazy)`
is the currently deprecated since the 2.9 but still in the doc http://www.eclipse.org/xtend/documentation/204_activeannotations.html#active-annotation-compiler-tester
Please update this. it is the entry to the language and should not be deprecated.

**Comment by cdietrich** [comment]
did you consider to simply add the missing test dependency. for sure this should no be a runtime depenency 

e.g.

```
<dependency>
    <groupId>org.eclipse.xtext</groupId>
    <artifactId>org.eclipse.xtext.xbase.testing</artifactId>
    <version>2.14.0</version>
    <scope>test</scope>
</dependency>
```

**Comment by cdietrich** [comment]
And I think we don’t have a replacement for the deprecated stuff

**Comment by cdietrich** [comment]
=> we should update the docs regarding maven and the test

**Comment by Lexanius** [comment]
In your code you use    
`extension XtendCompilerTester compile = XtendCompilerTester.newXtendCompilerTester(class.classLoader)`

**Comment by Lexanius** [comment]
Additional a Question, why it will the code

```
            @ExceptionConstructor
            class IllegalFileCompilation {
            }
```
To this:  
```
/* @ExceptionConstructor */@SuppressWarnings("all")
public class IllegalFileCompilation {
```

and a `import` or `package` is needed to compile right?
Working examples:

```
            import «ExceptionConstructor.name»
            
            @ExceptionConstructor
            class IllegalFileCompilation {
            }
```
or:
```
            package generator.annotation
            
            @ExceptionConstructor
            class IllegalFileCompilation {
            }
```

**Comment by cdietrich** [comment]
cant tell cause i dont have your complete code

**Comment by cdietrich** [comment]
Fixed. new website should be live in a few mins
