### ISSUE TITLE
How to copy a field.initalizer in AA

### ISSUE THREAD

**Issue by Lexanius** [eclipse/xtext-xtend#496]
Hi Team,

## The Problem
i want to copy only copy a field initalizer with AA, so that the original and a new field have the same initializer.

E.g.: 
```xtend
@Annotation
class Foo {
    var LogLevel level = LogLevel.ERROR
}
```

should create 2 classes:
```java
public class Foo {
    private LogLevel level = LogLevel.ERROR
}

public class FooBar {
    protected LogLevel level = LogLevel.ERROR
}
```
### what i have done
If write something like this:
```xtend

def addField(MutableClassDeclaration cls, FieldDeclaration field) {
    cls.addField(field.simpleName, [
         type = field.type
         visibility = Visibility.PROTECTED
          initializer = field.initializer
     ])
```
the new field has the right initalizer, but the initalizer of the original is null now. It is not possible to include the initalizer in a `StringConcatenationClient` because it is not evaluated and print the raw text.

### not working with StringConcatenationClient
A example that not work:
```xtend
@Annotation
class Foo {
    var Log.LogLevel level =  new Function0<Log.LogLevel >() {

        override apply() {
            var a = 1;
            Log.LogLevel.ERROR
        }
    }.apply()
}

def addField(MutableClassDeclaration cls, FieldDeclaration field) {
    cls.addField(field.simpleName, [
         type = field.type
         visibility = Visibility.PROTECTED
          initializer = '''«field.initializer»'''
     ])
```

it returns (java-class)
```java
public class FooBaz {
    protected Log.LogLevel level =  new Function0<Log.LogLevel >() {

        override apply() {
            var a = 1;
            Log.LogLevel.ERROR
        }
    }.apply();
}
```
The initalizerit is not compiled yet. 

Maybe it also help this guy too: https://stackoverflow.com/questions/50424202/how-to-expand-field-initializers-in-xtend-annotation-processor 

## Maybe Solution:

* give the Expression a way to include in StringConcatenationClient more times
* not delete the old initalizer after evaluated.

Greetings

Lexanius

**Comment by cdietrich** [comment]
i dont know of any way to achieve that. @szarnekow do you?

**Comment by holgerschill** [comment]
You need to copy the initializer with copyWithProxies. Due to containment in EMF it would get removed from the original place.

**Comment by cdietrich** [comment]
@holgerschill i doubt this will work typesystem wise

**Comment by cdietrich** [comment]
@Lexanius did you consider to infer a factory method and call that from both initializer places?

**Comment by Lexanius** [comment]
> @Lexanius did you consider to infer a factory method and call that from both initializer places?

not yet.

> You need to copy the initializer with copyWithProxies. Due to containment in EMF it would get removed from the original place.

Where i found the method `copyWithProxies`?

**Comment by szarnekow** [comment]
> Where i found the method copyWithProxies?

I'm afraid there is no such API for the Active Annotations.

**Comment by szarnekow** [comment]
Why do you want to copy the initializer?

**Comment by Lexanius** [comment]
Sry for the delay. 

I could not found the factory method.

**Comment by cdietrich** [comment]
so i mean infer it

inferrer

public Type initializeXyz() {
bodyhere}

for the field

body = '''initializeXyz()''''

**Comment by Lexanius** [comment]
> so i mean infer it
> 
> inferrer
> 
> public Type initializeXyz() {
> bodyhere}
> 
> for the field
> 
> body = '''initializeXyz()''''

not work, same problem like: `initializer = '''«field.initializer()»'''`

If i try to copy the expression:
```
                val expressionImpl = new ExpressionImpl()
                val fieldInitializer = field.initializer
                val expressionImpl2 = fieldInitializer as ExpressionImpl
                expressionImpl.delegate = (expressionImpl2).delegate
                expressionImpl.compilationUnit = expressionImpl2.compilationUnit
                initializer = expressionImpl
```

I get this error-message:

```
Error during annotation processing:
java.lang.ClassCastException: org.eclipse.xtend.core.macro.declaration.ExpressionImpl cannot be cast to org.eclipse.xtend.core.macro.declaration.ExpressionImpl
	at project.annotation.BuilderProcessor$Util.addGetterSetterField(BuilderProcessor.java:196)
	at project.annotation.BuilderProcessor$Util.lambda$6(BuilderProcessor.java:183)
	at org.eclipse.xtend.core.macro.declaration.JvmTypeDeclarationImpl.addField(JvmTypeDeclarationImpl.java:103)
	at project.annotation.BuilderProcessor$Util.addBuilderField(BuilderProcessor.java:185)
	at project.annotation.BuilderProcessor$Util.lambda$1(BuilderProcessor.java:120)
	at com.google.common.collect.Iterables$4.lambda$forEach$0(Iterables.java:581)
	at com.google.common.collect.Iterables$5.lambda$forEach$0(Iterables.java:624)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.google.common.collect.Iterables$5.forEach(Iterables.java:621)
	at com.google.common.collect.Iterables$4.forEach(Iterables.java:578)
	at project.annotation.BuilderProcessor$Util.createBuilder(BuilderProcessor.java:122)
	at project.annotation.BuilderProcessor.doTransform(BuilderProcessor.java:721)
	at org.eclipse.xtend.lib.macro.AbstractClassProcessor.doTransform(AbstractClassProcessor.java:42)

```

**Comment by cdietrich** [comment]
No just call the init method by naming convention

**Comment by cdietrich** [comment]
@Lexanius here is an example

```
package anno

import org.eclipse.xtend.lib.macro.AbstractClassProcessor
import org.eclipse.xtend.lib.macro.Active
import org.eclipse.xtend.lib.macro.RegisterGlobalsContext
import org.eclipse.xtend.lib.macro.TransformationContext
import org.eclipse.xtend.lib.macro.declaration.ClassDeclaration
import org.eclipse.xtend.lib.macro.declaration.MutableClassDeclaration

@Active(MyAnnoProcessor)
annotation MyAnno {
}

class MyAnnoProcessor extends AbstractClassProcessor {

	override doRegisterGlobals(ClassDeclaration annotatedClass, extension RegisterGlobalsContext context) {
		context.registerClass(annotatedClass.fooName)
	}

	def getFooName(ClassDeclaration annotatedClass) {
		annotatedClass.qualifiedName + "Foo"
	}

	override doTransform(MutableClassDeclaration annotatedClass, extension TransformationContext context) {
		val field = annotatedClass.declaredFields.head
		if (field !== null) {
			annotatedClass.addMethod("initTheFoo") [
				body = field.initializer
				returnType = field.type
				static = true;
			]
			field.initializer = '''initTheFoo()'''
			context.findClass(annotatedClass.fooName) => [f|
				f.addField(field.simpleName) [
					type = field.type
					initializer = '''«annotatedClass».initTheFoo()'''
				]
			]
		}
		super.doTransform(annotatedClass, context)
	}

}

```
