### ISSUE TITLE
Fix broken org.eclipse.xtend.ide.tests.quickfix.QuickfixTest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#521]
Hello @meysholdt `org.eclipse.xtend.ide.tests.quickfix.QuickfixTest` seems to be broken now.
is it possible this is related to your recent changes? Thanks, Christian

**Comment by cdietrich** [comment]
```
java.lang.RuntimeException: No Context for JvmGenericType.members[1]->JvmOperation.returnType->XComputedTypeReference could be found

Stacktrace

org.eclipse.emf.common.util.WrappedException: java.lang.RuntimeException: No Context for JvmGenericType.members[1]->JvmOperation.returnType->XComputedTypeReference could be found
	at org.eclipse.xtend.ide.tests.quickfix.QuickfixTest.unnecessaryModifier_05(QuickfixTest.java:7190)
Caused by: java.lang.RuntimeException: No Context for JvmGenericType.members[1]->JvmOperation.returnType->XComputedTypeReference could be found
	at org.eclipse.xtend.ide.tests.quickfix.QuickfixTest.unnecessaryModifier_05(QuickfixTest.java:7190)

```

**Comment by cdietrich** [comment]
@meysholdt is it possible change serializer support for xbase langs is very insufficient? why does it try to serialize the inferred objects at all?

**Comment by miklossy** [comment]
I have also seen that exception in https://github.com/eclipse/xtext-xtend/issues/408

**Comment by meysholdt** [comment]
I'll look at it later today

**Comment by cdietrich** [comment]
is fixed now. thx @meysholdt

**Comment by meysholdt** [comment]
build is green again.
