### ISSUE TITLE
Code genereated via Xtend 2.14 Annotation Processor incompatible with java 7

### ISSUE THREAD

**Issue by olga-kr** [eclipse/xtext-xtend#560]
Hi!
We use xtend annotation processing and have upgraded xtend version up to 2.14 recently. Now there's issue with java 7 ClassLoader and @Pure annotation.
Stacktrace:
Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/xtext/xbase/lib/Pure : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

**Comment by cdietrich** [comment]
we no longer support java 7

**Comment by kthoms** [comment]
Or stick to an older Xtend version. But we won't resume builds for Java 7.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-lib/issues/45 and https://github.com/eclipse/xtext-lib/issues/51

**Comment by cdietrich** [comment]
@olga-kr any feedback on this issue?

**Comment by olga-kr** [comment]
Oh , sorry.
We decided to stop java 7 support in our project too.
