### ISSUE TITLE
'Cannot set annotation values of type java.util.ArrayList' when ready nested annotations in annotation processor

### ISSUE THREAD

**Issue by patm0le** [eclipse/xtext-xtend#624]
When I try to read annotations in an annotation processor I get errors when there are nested annotations. In my project annotations are nested up to 6 levels but the problem also occurs in the attached tiny example project.
[active-annotation-list-value-ArrayList-Problem.zip](https://github.com/eclipse/xtext-xtend/files/2545922/active-annotation-list-value-ArrayList-Problem.zip)

The following error occurs:
> Error during annotation processing:
java.lang.IllegalArgumentException: Cannot set annotation values of type java.util.ArrayList
	at org.eclipse.xtend.core.macro.declaration.AnnotationReferenceBuildContextImpl._internalSet(AnnotationReferenceBuildContextImpl.java:230)
	at org.eclipse.xtend.core.macro.declaration.AnnotationReferenceBuildContextImpl.internalSet(AnnotationReferenceBuildContextImpl.java:921)
	at org.eclipse.xtend.core.macro.declaration.AnnotationReferenceBuildContextImpl.set(AnnotationReferenceBuildContextImpl.java:136)
	at org.eclipse.xtend.core.macro.declaration.CompilationUnitImpl.translateAnnotation(CompilationUnitImpl.java:1635)
	at org.eclipse.xtend.core.macro.declaration.CompilationUnitImpl.translate(CompilationUnitImpl.java:1582)
	at org.eclipse.xtend.core.macro.declaration.CompilationUnitImpl.evaluate(CompilationUnitImpl.java:1557)
	at org.eclipse.xtend.core.macro.declaration.CompilationUnitImpl.translateAnnotationValue(CompilationUnitImpl.java:1231)
	at org.eclipse.xtend.core.macro.declaration.XtendAnnotationReferenceImpl.translateAnnotationValue(XtendAnnotationReferenceImpl.java:132)
	at org.eclipse.xtend.core.macro.declaration.XtendAnnotationReferenceImpl.getValue(XtendAnnotationReferenceImpl.java:97)
	at org.eclipse.xtend.core.macro.declaration.XtendAnnotationReferenceImpl.getAnnotationArrayValue(XtendAnnotationReferenceImpl.java:146)
	at xtend.activeannotations.annotation.Annotation1Config.<init>(Annotation1Config.java:24)
	at xtend.activeannotations.annotation.AnnotationsProcessor.lambda$9(AnnotationsProcessor.java:82)
	at com.google.common.collect.Iterables$4.lambda$forEach$0(Iterables.java:581)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.google.common.collect.Iterables$4.forEach(Iterables.java:578)
	at xtend.activeannotations.annotation.AnnotationsProcessor.readConfig(AnnotationsProcessor.java:84)
	at xtend.activeannotations.annotation.AnnotationsProcessor.doRegisterGlobals(AnnotationsProcessor.java:43)
	at xtend.activeannotations.annotation.AnnotationsProcessor.lambda$2(AnnotationsProcessor.java:37)
	at com.google.common.collect.Iterables$6.lambda$forEach$0(Iterables.java:748)
	at com.google.common.collect.Iterables$4.lambda$forEach$0(Iterables.java:581)
	at java.lang.Iterable.forEach(Unknown Source)
	at com.google.common.collect.Iterables$4.forEach(Iterables.java:578)
	at com.google.common.collect.Iterables$6.forEach(Iterables.java:748)
	at xtend.activeannotations.annotation.AnnotationsProcessor.doRegisterGlobals(AnnotationsProcessor.java:39)

The error occurs in Eclipse markers and when compiling with maven (right side version after workaround):
![annotationreferencebuildcontextimpl-errormessage](https://user-images.githubusercontent.com/12173934/47965616-9e6d5580-e049-11e8-880c-7ce49e311591.png)

It doesn't appear when there's only 1 element in the array and no square braces are used (this screenshot is NOT from the attached example project).
![singleelementarray](https://user-images.githubusercontent.com/12173934/47965617-9e6d5580-e049-11e8-9b10-7c905186f1af.png)

As I don't know the codebase I just tried a dirty workaround near the root of the exception ( AnnotationReferenceBuildContextImpl ). I just replaced the Iterable value with an array and now it works fine for me.
![annotationreferencebuildcontextimpl-dirtyworkaround](https://user-images.githubusercontent.com/12173934/47965615-9dd4bf00-e049-11e8-9a7f-033637a420b3.png)

I'm sure I'm not the first one to read nested annotations in annotations processors so maybe there's something I'm doing completely wrong. So far I created about 20 ActiveAnnotations (with simpler annotation structures) and had no problem.

**Comment by cdietrich** [comment]
i assume this was never working: https://groups.google.com/forum/#!topic/xtend-lang/QYfR0oMdU40

**Comment by cdietrich** [comment]
Fixed in 2.16
