### ISSUE TITLE
NPE in StandardTypeReferenceOwner.<init>

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#779]
NPE in StandardTypeReferenceOwner.<init>

this happens to me whilst editing WorkspaceManager class
(e.g. adding removing methods)

```
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.typesystem.references.StandardTypeReferenceOwner.<init>(StandardTypeReferenceOwner.java:46)
	at org.eclipse.xtext.xbase.typesystem.references.StandardTypeReferenceOwner.<init>(StandardTypeReferenceOwner.java:42)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.newTypeReferenceOwner(AbstractXbaseCompiler.java:131)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.getClosureOperationParameterType(XbaseCompiler.java:1784)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.toLambda(XbaseCompiler.java:1811)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler._toJavaStatement(XbaseCompiler.java:1643)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:357)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler._toJavaStatement(XbaseCompiler.java:1032)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:371)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler._toJavaStatement(XbaseCompiler.java:414)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:353)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.compile(AbstractXbaseCompiler.java:294)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.compile(AbstractXbaseCompiler.java:274)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.compile(JvmModelGenerator.java:1059)
	at org.eclipse.xtend.core.compiler.XtendGenerator.compile(XtendGenerator.java:213)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateExecutableBody(JvmModelGenerator.java:1036)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._generateMember(JvmModelGenerator.java:800)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateMember(JvmModelGenerator.java:1657)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.lambda$generateMembersInBody$2(JvmModelGenerator.java:292)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.eclipse.xtext.xbase.compiler.LoopExtensions.lambda$forEach$0(LoopExtensions.java:38)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.xtext.xbase.compiler.LoopExtensions.forEach(LoopExtensions.java:40)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateMembersInBody(JvmModelGenerator.java:295)
	at org.eclipse.xtend.core.compiler.XtendGenerator.generateMembersInBody(XtendGenerator.java:572)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._generateBody(JvmModelGenerator.java:269)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateBody(JvmModelGenerator.java:1629)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateType(JvmModelGenerator.java:226)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._internalDoGenerate(JvmModelGenerator.java:213)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.internalDoGenerate(JvmModelGenerator.java:1612)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.doGenerate(JvmModelGenerator.java:196)
	at org.eclipse.xtend.core.compiler.XtendGenerator.doGenerate(XtendGenerator.java:95)
	at org.eclipse.xtend.core.compiler.XtendGenerator.doGenerate(XtendGenerator.java:111)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:43)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:183)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:172)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doGenerate(ParallelBuilderParticipant.java:343)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant$1.run(ParallelBuilderParticipant.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/buglist.cgi?quicksearch=StandardTypeReferenceOwner&list_id=18633878 too

**Comment by cdietrich** [comment]
[xtend-issue-779.zip](https://github.com/eclipse/xtext-xtend/files/3076193/xtend-issue-779.zip)
small reproducing sample project

**Comment by cdietrich** [comment]
[xtend-issue-779.zip](https://github.com/eclipse/xtext-xtend/files/3076196/xtend-issue-779.zip)
small reproducing sample project

**Comment by cdietrich** [comment]
the bad JvmOperation is 

JvmOperation:  (eProxyURI: platform:/resource/demo/src/demo/BuildManager2.xtend#/1/@members.0/@members.0)

**Comment by cdietrich** [comment]
@szarnekow is there a resolve for the operation missing? shouldnt that happen automatically?

```
	protected ITreeAppendable toLambda(XClosure closure, ITreeAppendable b, LightweightTypeReference type,
			JvmOperation operation, boolean writeExplicitTargetType) {
		if (operation.eIsProxy()) {
			operation = (JvmOperation) EcoreUtil.resolve(operation, closure);
		}
```

**Comment by cdietrich** [comment]
could this be a side effect of the xbase diagnostician changes

**Comment by szarnekow** [comment]
This should certainly be a resolved JvmOperation. Thank you for the repro. This needs some further investigation.

**Comment by cdietrich** [comment]
@szarnekow i tried it and it really seems to be caused by xbase diagnistician changes

**Comment by cdietrich** [comment]
@szarnekow will move to 2.19.
would be nice if we can have a look together. this really hurts when working in xtext-core

**Comment by cdietrich** [comment]
will remove milestone
