### ISSUE TITLE
Tests crash on CBI

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#801]
https://jenkins.eclipse.org/xtext/job/xtext-xtend/job/master/54/console
```
[INFO] --- tycho-surefire-plugin:1.4.0:test (default-test) @ org.eclipse.xtend.ide.swtbot.tests ---
[INFO] Expected eclipse log file: /home/jenkins/workspace/xtext-xtend_master-CZ6MQ7K3F54I6ECVAJOY5S5BWV6SPAS3CFPK73ZFQFHMBDDXMCYA/org.eclipse.xtend.ide.swtbot.tests/target/work/data/.metadata/.log
[INFO] Command line:
	[/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-6.fc29.x86_64/jre/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Xmx2G, -Dorg.eclipse.swtbot.keyboard.layout=EN_US, -Dorg.eclipse.swtbot.playback.delay=60, -Dosgi.clean=true, -jar, /home/jenkins/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.4.0.v20161219-1356/org.eclipse.equinox.launcher-1.4.0.v20161219-1356.jar, -data, /home/jenkins/workspace/xtext-xtend_master-CZ6MQ7K3F54I6ECVAJOY5S5BWV6SPAS3CFPK73ZFQFHMBDDXMCYA/org.eclipse.xtend.ide.swtbot.tests/target/work/data, -install, /home/jenkins/workspace/xtext-xtend_master-CZ6MQ7K3F54I6ECVAJOY5S5BWV6SPAS3CFPK73ZFQFHMBDDXMCYA/org.eclipse.xtend.ide.swtbot.tests/target/work, -configuration, /home/jenkins/workspace/xtext-xtend_master-CZ6MQ7K3F54I6ECVAJOY5S5BWV6SPAS3CFPK73ZFQFHMBDDXMCYA/org.eclipse.xtend.ide.swtbot.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /home/jenkins/workspace/xtext-xtend_master-CZ6MQ7K3F54I6ECVAJOY5S5BWV6SPAS3CFPK73ZFQFHMBDDXMCYA/org.eclipse.xtend.ide.swtbot.tests/target/surefire.properties, -nouithread, -pluginCustomization, /home/jenkins/workspace/xtext-xtend_master-CZ6MQ7K3F54I6ECVAJOY5S5BWV6SPAS3CFPK73ZFQFHMBDDXMCYA/org.eclipse.xtend.ide.swtbot.tests/../releng/org.eclipse.xtend.tycho.tests.parent/pluginCustomization.ini]
gogo: InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.System.getenv(System.java:897)
	at org.apache.felix.gogo.options.Options.<init>(Options.java:309)
	at org.apache.felix.gogo.options.Options.compile(Options.java:118)
	at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:71)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1511
	at java.lang.ProcessEnvironment.environ(Native Method)
	at java.lang.ProcessEnvironment.<clinit>(ProcessEnvironment.java:70)
	... 18 more
An error has occurred. See the log file
```

**Comment by cdietrich** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1445 says this could be a race

**Comment by cdietrich** [comment]
TODO: observe if happens again

**Comment by cdietrich** [comment]
did not happen again
