### ISSUE TITLE
Xtend Plugin - {IllegalArgumentException + IOException: Invalid file name: ':'} - IntelliJ IDEA 2019.1

### ISSUE THREAD

**Issue by dmitry-v-vlasov** [eclipse/xtext-xtend#892]
**Xtend Support (2.10.0):**
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'ancestor' of com/intellij/openapi/vfs/VfsUtilCore.isAncestor must not be null
	at com.intellij.openapi.vfs.VfsUtilCore.$$$reportNull$$$0(VfsUtilCore.java)
	at com.intellij.openapi.vfs.VfsUtilCore.isAncestor(VfsUtilCore.java)
	at org.eclipse.xtend.core.idea.config.XtendProjectConfigurator$8.apply(XtendProjectConfigurator.java:294)
	at org.eclipse.xtend.core.idea.config.XtendProjectConfigurator$8.apply(XtendProjectConfigurator.java:290)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.findFirst(IteratorExtensions.java:102)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.findFirst(IterableExtensions.java:80)
	at org.eclipse.xtend.core.idea.config.XtendProjectConfigurator.addAsSourceFolder(XtendProjectConfigurator.java:297)
	at org.eclipse.xtend.core.idea.config.XtendProjectConfigurator.createOutputFolders(XtendProjectConfigurator.java:208)
	at org.eclipse.xtend.core.idea.framework.XtendSupportConfigurable.addSupport(XtendSupportConfigurable.java:46)
	at org.eclipse.xtend.core.idea.framework.XtendFrameworkDetector.setupFacet(XtendFrameworkDetector.java:64)
	at com.intellij.framework.detection.impl.FacetBasedDetectedFrameworkDescription.doSetup(FacetBasedDetectedFrameworkDescription.java:115)
	at com.intellij.framework.detection.impl.FacetBasedDetectedFrameworkDescriptionImpl.setupFramework(FacetBasedDetectedFrameworkDescriptionImpl.java:53)
	at com.intellij.framework.detection.impl.FrameworkDetectionUtil.lambda$setupFrameworks$0(FrameworkDetectionUtil.java:102)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:92)
	at com.intellij.framework.detection.impl.FrameworkDetectionUtil.setupFrameworks(FrameworkDetectionUtil.java:88)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.showSetupFrameworksDialog(FrameworkDetectionManager.java:239)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.access$200(FrameworkDetectionManager.java:43)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager$3.actionPerformed(FrameworkDetectionManager.java:181)
	at com.intellij.notification.NotificationAction.actionPerformed(NotificationAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:252)
	at com.intellij.notification.Notification.fire(Notification.java:229)
	at com.intellij.notification.impl.NotificationsManagerImpl$14.linkSelected(NotificationsManagerImpl.java:783)
	at com.intellij.notification.impl.NotificationsManagerImpl$14.linkSelected(NotificationsManagerImpl.java:780)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:356)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:330)
	at com.intellij.notification.impl.NotificationsManagerImpl$HoverAdapter.handleEvent(NotificationsManagerImpl.java:901)
	at com.intellij.notification.impl.NotificationsManagerImpl$HoverAdapter.mouseReleased(NotificationsManagerImpl.java:840)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Xtext IDEA Core (2.10.0):**
```
Error during auto build.

java.lang.RuntimeException: java.io.IOException: Invalid file name: ':'
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:680)
	at org.eclipse.xtext.idea.build.XtextAutoBuilderComponent.internalBuild(XtextAutoBuilderComponent.java:875)
	at org.eclipse.xtext.idea.build.XtextAutoBuilderComponent$19.run(XtextAutoBuilderComponent.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Invalid file name: ':'
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.validateName(VirtualFileSystemEntry.java:274)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.createChildDirectory(VirtualFileSystemEntry.java:268)
	at com.intellij.openapi.vfs.VfsUtil.createDirectoryIfMissing(VfsUtil.java:350)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:73)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateFile(VirtualFileURIUtil.java:70)
	at org.eclipse.xtext.idea.resource.VirtualFileURIUtil.getOrCreateVirtualFile(VirtualFileURIUtil.java:54)
	at org.eclipse.xtext.idea.resource.IdeaResourceSetProvider$VirtualFileBasedUriHandler$1.run(IdeaResourceSetProvider.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at org.eclipse.xtext.idea.resource.IdeaResourceSetProvider$VirtualFileBasedUriHandler.flushToDisk(IdeaResourceSetProvider.java:169)
	at org.eclipse.xtext.idea.build.XtextAutoBuilderComponent$22.run(XtextAutoBuilderComponent.java:867)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cdietrich** [comment]
the idea generator is no longer supported.
this looks like some versions not matching
