### ISSUE TITLE
Reading files in AA might lead to deadlock

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#991]
I see deadlocks in the AA Processor for the template files when i do updates to fowler.ui on command line (or do a touch on all xtend and java files and restart eclipse)

i still dont complete understand the deadlock

[jstack.txt](https://github.com/eclipse/xtext-xtend/files/4046247/jstack.txt)

**Comment by cdietrich** [comment]
```
"ParallelGenerator-0" #94 prio=5 os_prio=0 tid=0x00007f4d683b4000 nid=0x2c83 in Object.wait() [0x00007f4ce0413000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:316)
	- locked <0x000000008e089540> (a java.lang.Object)
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:205)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:297)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2243)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1542)
	at org.eclipse.core.internal.resources.File.refreshLocal(File.java:319)
	at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl$WorkbenchHelper.createPlatformResourceInputStream(PlatformResourceURIHandlerImpl.java:205)
	at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl.createInputStream(PlatformResourceURIHandlerImpl.java:525)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:298)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:354)
	at org.eclipse.xtend.core.macro.AbstractFileSystemSupport.getContentsAsStream(AbstractFileSystemSupport.java:236)
	at org.eclipse.xtend.core.macro.AbstractFileSystemSupport.getContents(AbstractFileSystemSupport.java:66)
	at org.eclipse.xtend.core.macro.declaration.ChangeListenerAddingFileSystemSupport.getContents(ChangeListenerAddingFileSystemSupport.java:76)
```
is this guy waiting for workspace lock?
